-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgRuinSgNsMFbCwlcZ
vRc5WCAg+Jdujm2xBh4pqfn2fdegCgYIKoZIzj0DAQehRANCAATUaBklUv+F8nPn
AzuaOSacdECX0rRB5tE8JEGF/70/lTNr9P2nRc8Kzo90zmWGTcnbjD5xa1bgHVkc
2IjD0riO
-----END PRIVATE KEY-----