workflows:
  ios-build:
    name: iOS build – Device Tuner PRO 26
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      vars:
        XCODE_PROJECT: "CleanerGuru.xcodeproj"
        XCODE_SCHEME: "CleanerGuru"
        APPLE_TEAM_ID: "2ZFFN6CVB4"
        CERTIFICATE_PATH: "ios_distribution.p12"
        CERTIFICATE_PASSWORD: "123456"
        PROVISIONING_PROFILE_PATH: "ios.mobileprovision"
        APP_STORE_CONNECT_API_KEY_PATH: "AuthKey_6V3PP83474.p8"

    scripts:
      - name: Install Fastlane
        script: |
          gem install fastlane --no-document

      - name: Import Certificate
        script: |
          security import "$CERTIFICATE_PATH" -P "$CERTIFICATE_PASSWORD" -A

      - name: Increment build number
        script: |
          currentBuildNumber=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "sources/Info.plist")
          newBuildNumber=$((currentBuildNumber + 1))
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $newBuildNumber" "sources/Info.plist"
          echo "Build number incremented to $newBuildNumber"

      - name: Build & Sign IPA
        script: |
          fastlane gym \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --clean \
            --export_method app-store \
            --output_directory build/ios/ipa \
            --output_name DeviceTunerPro26.ipa \
            --export_options "./exportOptions.plist" \
            --xcargs "DEVELOPMENT_TEAM=$APPLE_TEAM_ID CODE_SIGN_STYLE=Manual PROVISIONING_PROFILE_SPECIFIER=$(basename $PROVISIONING_PROFILE_PATH .mobileprovision)"

    artifacts:
      - build/ios/ipa/*.ipa
