workflows:
  ios-build:
    name: iOS build – Device Tuner PRO 26
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      vars:
        XCODE_PROJECT: "CleanerGuru.xcodeproj"
        XCODE_SCHEME: "CleanerGuru"
        APPLE_TEAM_ID: "2ZFFN6CVB4"
        PROVISIONING_PROFILE_SPECIFIER: "ios"
        EXPORT_OPTIONS_PLIST: "./exportOptions.plist"
        CERTIFICATE_PATH: "./ios_distribution.p12"
        CERTIFICATE_PASSWORD: "123456"

    scripts:
      - name: Install Fastlane
        script: |
          gem install fastlane --no-document

      - name: Increment build number
        script: |
          PLIST_PATH="./sources/Info.plist"
          if [ -f "$PLIST_PATH" ]; then
            currentBuildNumber=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$PLIST_PATH")
            newBuildNumber=$((currentBuildNumber + 1))
            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $newBuildNumber" "$PLIST_PATH"
            echo "Build number incremented to $newBuildNumber"
          else
            echo "Info.plist not found at $PLIST_PATH"
            exit 1
          fi

      - name: Import certificate
        script: |
          security create-keychain -p "" build.keychain
          security import "$CERTIFICATE_PATH" -P "$CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k build.keychain
          security list-keychains -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain

      - name: Build & Sign IPA
        script: |
          fastlane gym \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --clean \
            --export_method app-store \
            --output_directory build/ios/ipa \
            --output_name DeviceTunerPro26.ipa \
            --export_options "$EXPORT_OPTIONS_PLIST" \
            --xcargs "DEVELOPMENT_TEAM=$APPLE_TEAM_ID PROVISIONING_PROFILE_SPECIFIER=$PROVISIONING_PROFILE_SPECIFIER CODE_SIGN_STYLE=Manual"

    artifacts:
      - build/ios/ipa/*.ipa
