workflows:
  ios-build:
    name: iOS build – Device Tuner PRO 26
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "CleanerGuru.xcodeproj"
        XCODE_SCHEME: "CleanerGuru"

    scripts:
      - name: Install Fastlane
        script: |
          gem install fastlane --no-document

      - name: Increment build number
        script: |
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $(date +%s)" CleanerGuru/Info.plist

      - name: Build & Sign IPA (Automatic Signing)
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/CleanerGuru.xcarchive \
            archive \
            -allowProvisioningUpdates

          xcodebuild \
            -exportArchive \
            -archivePath build/CleanerGuru.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist /usr/libexec/PlistBuddy \
            -allowProvisioningUpdates

    artifacts:
      - build/ipa/*.ipa
