workflows:
  ios-build:
    name: iOS build – Device Tuner PRO 26
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      vars:
        XCODE_PROJECT: "CleanerGuru.xcodeproj"
        XCODE_SCHEME: "CleanerGuru"
        APPLE_ID: $APPLE_ID
        APPLE_TEAM_ID: $APPLE_TEAM_ID
        APP_NAME: $APP_NAME

    scripts:
      - name: Install Fastlane
        script: |
          gem install fastlane --no-document

      - name: Increment build number
        script: |
          currentBuildNumber=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "Sources/Info.plist")
          newBuildNumber=$((currentBuildNumber + 1))
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $newBuildNumber" "Sources/Info.plist"
          echo "Build number incremented to $newBuildNumber"

      - name: Build IPA
        script: |
          fastlane gym \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --clean \
            --export_method app-store \
            --output_directory build/ios/ipa \
            --output_name DeviceTunerPro26.ipa \
            --xcargs "DEVELOPMENT_TEAM=$APPLE_TEAM_ID CODE_SIGN_STYLE=Automatic" \
            --allowProvisioningUpdates

      - name: Upload to TestFlight
        script: |
          fastlane deliver \
            --ipa "build/ios/ipa/DeviceTunerPro26.ipa" \
            --skip_metadata true \
            --skip_screenshots true \
            --username "$APPLE_ID" \
            --submit_for_review true \
            --automatic_release false

    artifacts:
      - build/ios/ipa/*.ipa
