workflows:
  ios-build:
    name: iOS Build – CleanerGuru
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      vars:
        XCODE_PROJECT: CleanerGuru.xcodeproj
        XCODE_SCHEME: CleanerGuru

    scripts:
      - name: Archive app
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/CleanerGuru.xcarchive \
            clean archive

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/CleanerGuru.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        submit_to_testflight: true
