workflows:
  ios-build:
    name: iOS build – Device Tuner PRO 26
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      vars:
        # Xcode project and scheme
        XCODE_PROJECT: "CleanerGuru.xcodeproj"
        XCODE_SCHEME: "CleanerGuru"
        APP_STORE_CONNECT_API_KEY_PATH: "AuthKey_6V3PP83474.p8"
        APP_STORE_CONNECT_KEY_ID: "6V3PP83474"
        APP_STORE_CONNECT_ISSUER_ID: "26bb7108-fb21-4a1d-bf89-a194949bc56a"

    scripts:
      - name: Install CocoaPods
        script: |
          cd ios || true
          pod install || true

      - name: Increment build number
        script: |
          cd ios || true
          # Read current build number from Info.plist
          currentBuildNumber=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "Info.plist")
          # Increment by 1
          newBuildNumber=$((currentBuildNumber + 1))
          # Update Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $newBuildNumber" "Info.plist"
          echo "Build number incremented: $newBuildNumber"

      - name: Build and archive IPA
        script: |
          xcode-project build-ipa             --project "$XCODE_PROJECT"             --scheme "$XCODE_SCHEME"

      - name: Upload to TestFlight / App Store
        script: |
          gem install fastlane --no-document
          cd ios || true
          fastlane deliver             --ipa build/ios/ipa/*.ipa             --skip_metadata true             --skip_screenshots true             --skip_app_version_update true             --api_key_path "$APP_STORE_CONNECT_API_KEY_PATH"

    artifacts:
      - build/ios/ipa/*.ipa
