workflows:
  ios-build:
    name: iOS build – Device Tuner PRO 26
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      vars:
        XCODE_PROJECT: CleanerGuru.xcodeproj
        XCODE_SCHEME: CleanerGuru

    scripts:
      - name: Build IPA
        script: |
          xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -archivePath build/CleanerGuru.xcarchive \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates

          xcodebuild -exportArchive \
            -archivePath build/CleanerGuru.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/ipa

    artifacts:
      - build/ipa/*.ipa

    publishing:
      app_store_connect:
        use_integration: true
