workflows:
  ios-build:
    name: iOS build – Device Tuner PRO 26
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      vars:
        XCODE_PROJECT: "CleanerGuru.xcodeproj"
        XCODE_SCHEME: "CleanerGuru"
        APPLE_TEAM_ID: "2ZFFN6CVB4"
        IPA_OUTPUT_NAME: "DeviceTunerPro26.ipa"

    scripts:
      - name: Install Fastlane
        script: |
          gem install fastlane --no-document

      - name: Increment build number
        script: |
          currentBuildNumber=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "Info.plist")
          newBuildNumber=$((currentBuildNumber + 1))
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $newBuildNumber" "Info.plist"
          echo "Build number incremented to $newBuildNumber"

      - name: Build IPA
        script: |
          fastlane gym \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --clean \
            --export_method app-store \
            --output_directory build/ios/ipa \
            --output_name "$IPA_OUTPUT_NAME" \
            --xcargs "DEVELOPMENT_TEAM=$APPLE_TEAM_ID CODE_SIGN_STYLE=Automatic"

      - name: Upload to TestFlight
        script: |
          fastlane deliver \
            --ipa "build/ios/ipa/$IPA_OUTPUT_NAME" \
            --skip_metadata true \
            --skip_screenshots true \
            --skip_app_version_update true \
            --api_key_path "AuthKey_6V3PP83474.p8"

    artifacts:
      - build/ios/ipa/*.ipa
