workflows:
  ios-build:
    name: iOS build – Device Tuner PRO 26
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      vars:
        XCODE_PROJECT: "CleanerGuru.xcodeproj"
        XCODE_SCHEME: "CleanerGuru"
        APP_STORE_CONNECT_API_KEY_PATH: "AuthKey_6V3PP83474.p8"
        APP_STORE_CONNECT_KEY_ID: "6V3PP83474"
        APP_STORE_CONNECT_ISSUER_ID: "26bb7108-fb21-4a1d-bf89-a194949bc56a"

    scripts:
      - name: Install CocoaPods and Fastlane
        script: |
          cd ios || true
          pod install || true
          gem install fastlane --no-document

      - name: Increment build number and build IPA
        script: |
          cd ios || true
          # Increment build number
          currentBuildNumber=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "Info.plist")
          newBuildNumber=$((currentBuildNumber + 1))
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $newBuildNumber" "Info.plist"
          echo "Build number incremented: $newBuildNumber"
          # Build IPA using Fastlane gym
          fastlane gym \
            --scheme "CleanerGuru" \
            --project "CleanerGuru.xcodeproj" \
            --output_directory "../build/ios/ipa" \
            --output_name "DeviceTunerPro26.ipa" \
            --clean

      - name: Upload to TestFlight / App Store
        script: |
          cd ios || true
          fastlane deliver \
            --ipa "../build/ios/ipa/DeviceTunerPro26.ipa" \
            --skip_metadata true \
            --skip_screenshots true \
            --skip_app_version_update true \
            --api_key_path "AuthKey_6V3PP83474.p8"

    artifacts:
      - build/ios/ipa/*.ipa
