workflows:
  ios-build:
    name: iOS build – Device Tuner PRO 26
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      vars:
        XCODE_PROJECT: "CleanerGuru.xcodeproj"
        XCODE_SCHEME: "CleanerGuru"
        APPLE_TEAM_ID: "2ZFFN6CVB4"

    scripts:
      - name: Install Fastlane
        script: |
          gem install fastlane --no-document

      - name: Increment build number
        script: |
          PLIST_PATH="Sources/Info.plist"

          /usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$PLIST_PATH" || \
          /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string 1" "$PLIST_PATH"

          currentBuildNumber=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$PLIST_PATH")
          newBuildNumber=$((currentBuildNumber + 1))

          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $newBuildNumber" "$PLIST_PATH"

          echo "Build number incremented to $newBuildNumber"

      - name: Build & Sign IPA (Automatic Signing)
        script: |
          fastlane gym \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --clean \
            --export_method app-store \
            --output_directory build/ios/ipa \
            --output_name DeviceTunerPro26.ipa \
            --xcargs "DEVELOPMENT_TEAM=$APPLE_TEAM_ID CODE_SIGN_STYLE=Automatic -allowProvisioningUpdates"

    artifacts:
      - build/ios/ipa/*.ipa
