workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    environment:
      vars:
        XCODE_PROJECT: CleanerGuru.xcodeproj
        XCODE_SCHEME: CleanerGuru
        APP_STORE_CONNECT_API_KEY_PATH: AuthKey_6V3PP83474.p8
        APP_STORE_CONNECT_KEY_ID: 6V3PP83474
        APP_STORE_CONNECT_ISSUER_ID: 26bb7108-fb21-4a1d-bf89-a194949bc56a
      node: stable
      cocoapods: default
      xcode: latest
      flutter: none
    scripts:
      - name: Install dependencies
        script: |
          gem install fastlane
          pod install --project-directory=.
      - name: Build and archive IPA
        script: |
          fastlane gym \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --clean \
            --export_method app-store \
            --output_directory build/ios/ipa \
            --output_name DeviceTunerPro26 \
            --xcargs "DEVELOPMENT_TEAM=2ZFFN6CVB4 CODE_SIGN_STYLE=Automatic"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key_path: $APP_STORE_CONNECT_API_KEY_PATH
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
