workflows:
  ios-build:
    name: iOS build – Device Tuner PRO 26
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      vars:
        # Only the required variables
        XCODE_PROJECT: CleanerGuru.xcodeproj
        XCODE_SCHEME: CleanerGuru

    scripts:
      - name: Install Fastlane
        script: |
          gem install fastlane --no-document

      - name: Increment build number
        script: |
          /usr/libexec/PlistBuddy -c "Print CFBundleVersion" "Info.plist" || echo "0" > tmp_build
          currentBuildNumber=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "Info.plist" 2>/dev/null || echo 0)
          newBuildNumber=$((currentBuildNumber + 1))
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $newBuildNumber" "Info.plist"
          echo "Build number incremented to $newBuildNumber"

      - name: Build IPA
        script: |
          xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -archivePath build/CleanerGuru.xcarchive \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates

          xcodebuild -exportArchive \
            -archivePath build/CleanerGuru.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/ipa

    artifacts:
      - build/ipa/*.ipa

    publishing:
      app_store_connect:
        use_integration: true
